// import './modules/theme';
// import './modules/lang';
// import './modules/aos';
import './modules/copyValue';
import './modules/generatePassword';
import './modules/resetEverything';
import './modules/changeCharacters';
import './modules/main-script';
import './modules/closeModal';
import './modules/lang';
